apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32500
  selector:
    app: $APP_NAME
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
    app: $APP_NAME
spec:
  selector:
    matchLabels:
      app: $APP_NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: $REGISTRY/$APP_NAME:latest
        ports:
        - containerPort: 5000
