apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32500
  selector:
    app: my-app
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: $REGISTRY/my-app:latest
        ports:
        - containerPort: 5000
