# To install:
# kubectl create namespace rabbit
# helm install my-rabbit stable/rabbitmq-ha --namespace rabbit -f rabbit-values.yaml

replicas: 3

service:
  type: NodePort 

rabbitmqUsername: guest
rabbitmqPassword: guest
